{"uuid": "c1e33a46-ab52-4536-88d0-cc7e11b21af6", "children": ["9fb8f061-5777-46c8-9665-341887ac837e", "cc9973e3-0eed-48a0-b5b7-9472c228e39c"], "befores": [{"name": "test_setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home\n\n", "trace": "  File \"C:\\Program Files (x86)\\Python\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Program Files (x86)\\Python\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Program Files (x86)\\Python\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"C:\\Users\\amal.mohamed.FLAIRSTECH\\PycharmProjects\\ScoutbeeAssignment\\OrangeHrmLiveWebSite\\Tests\\p_test.py\", line 22, in test_setup\n    driver = webdriver.Chrome(executable_path=\"../drivers/chromedriver.exe\")\n  File \"C:\\Program Files (x86)\\Python\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 73, in __init__\n    self.service.start()\n  File \"C:\\Program Files (x86)\\Python\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 81, in start\n    raise WebDriverException(\n"}, "start": 1585459174929, "stop": 1585459174932}], "start": 1585459174929, "stop": 1585459175462}