{"uuid": "83b5a63c-2f37-4292-8737-c74288a8bed0", "children": ["e58126b0-62bc-4917-ba84-f36c883e2918", "591abdb2-208d-432a-92a3-34d2677b20b7"], "befores": [{"name": "test_setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home\n\n", "trace": "  File \"C:\\Program Files (x86)\\Python\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Program Files (x86)\\Python\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Program Files (x86)\\Python\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"C:\\Users\\amal.mohamed.FLAIRSTECH\\PycharmProjects\\ScoutbeeAssignment\\OrangeHrmLiveWebSite\\Tests\\p_test.py\", line 22, in test_setup\n    driver = webdriver.Chrome(executable_path=\"../drivers/chromedriver.exe\")\n  File \"C:\\Program Files (x86)\\Python\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 73, in __init__\n    self.service.start()\n  File \"C:\\Program Files (x86)\\Python\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 81, in start\n    raise WebDriverException(\n"}, "start": 1585459605113, "stop": 1585459605115}], "start": 1585459605113, "stop": 1585459605725}