{"uuid": "d21a1448-f7e4-4d59-b28f-029a3bad4f51", "children": ["bbb2523b-6c08-4ee8-94f5-c699f3f81535", "cdd8b396-4c85-48ce-ad60-b1898cf08b38"], "befores": [{"name": "test_setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home\n\n", "trace": "  File \"C:\\Program Files (x86)\\Python\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Program Files (x86)\\Python\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Program Files (x86)\\Python\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"C:\\Users\\amal.mohamed.FLAIRSTECH\\PycharmProjects\\ScoutbeeAssignment\\OrangeHrmLiveWebSite\\Tests\\p_test.py\", line 22, in test_setup\n    driver = webdriver.Chrome(executable_path=\"../drivers/chromedriver.exe\")\n  File \"C:\\Program Files (x86)\\Python\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 73, in __init__\n    self.service.start()\n  File \"C:\\Program Files (x86)\\Python\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 81, in start\n    raise WebDriverException(\n"}, "start": 1585458917555, "stop": 1585458917556}], "start": 1585458917555, "stop": 1585458917754}